# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  leavemate:
    image: leavemate
    build:
      context: ./LeaveMateApp
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Sqlite=Data Source=/app/data/leavemate.db
    volumes:
      - ./LeaveMateApp/LeaveMate/data:/app/data
    ports:
      - "8080:8080"
  leavematetests:
    image: leavematetests
    build:
      context: .
      dockerfile: LeaveMateApp/LeaveMate.Tests/Dockerfile
